version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: creperia_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: creperia_db
      MYSQL_USER: creperia_user
      MYSQL_PASSWORD: creperia_password
    volumes:
      - ./mariadb_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: creperia_adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    depends_on:
      - mariadb
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: creperia_api
    ports:
      - "8081:8080"
    depends_on:
      - mariadb
    restart: unless-stopped

  webapp:
    build:
      context: .
      dockerfile: Dockerfile.webapp
    container_name: creperia_webapp
    ports:
      - "80:80"
    depends_on:
      - api
    restart: unless-stopped

volumes:
  mariadb_data: